
const SEARCHDOCTORS = 'DETAIL-DOCTOR'
const SEARCHUSERS = 'SEARCH-USERS'
const SEARCHSPECIALTIES = 'SEARCH-SPECIALTIES'
const SEARCHCLINICS = 'SEARCH-CLINICS'



export { SEARCHDOCTORS, SEARCHUSERS, SEARCHCLINICS, SEARCHSPECIALTIES }