
const SEARCHDOCTORS = 'DETAIL-DOCTOR'
const SEARCHUSERS = 'SEARCH-USERS'
const SEARCHSPECIALTIES = 'SEARCH-SPECIALTIES'
const SEARCHCLINICS = 'SEARCH-CLINICS'
const SEARCHOVERALL = 'SEARCH-OVERALL'




export { SEARCHDOCTORS, SEARCHUSERS, SEARCHCLINICS, SEARCHSPECIALTIES, SEARCHOVERALL }